### ISSUE TITLE
Tasks take longer to complete than their total time.

### ISSUE THREAD

**Issue by sasichkamega** [rafaelpernil2/ParallelPromises#13]
If there are 6 tasks of 1 second each, then they will perform more than six seconds divide by concurrency, if concurrency > 1. But if the concurrency is equal to one, then the total execution time is equal to the sum of the execution time of each task.

Code.

const parallel_promises = require("parallel-promises");
const perf_hooks = require("perf_hooks");

function wait1sec() {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 1000);
  }); 
}

(async () => {
  const tasks = [];
  for (let i = 0; i < 6; ++i) {
    tasks.push({
      function: wait1sec,
      args: []
    }); 
  }
  console.log("concurrency 1");
  let start = perf_hooks.performance.now();
  await parallel_promises.customPromiseAll(tasks, 1);
  let end = perf_hooks.performance.now();
  console.log("dt: %f", end - start);
  console.log("concurrency 2");
  start = perf_hooks.performance.now();
  await parallel_promises.customPromiseAll(tasks, 2);
  end = perf_hooks.performance.now();
  console.log("dt: %f", end - start);
})();

**Comment by rafaelpernil2** [comment]
Thank you for creating this issue. I found the bug 😄!

When pushing each custom promise into the execution array, I was calling this method `promiseList.slice(execLimit)`, which made each custom promise work with a different list of awaiting promises. Thus, when removing the finished ones, they were not being removed on all custom promise executions.

I simply moved it out of the .push call and it was fixed. This issue is already fixed on version 1.5.3 and I also added a test to cover this situation.

Thanks again for pointing out the error and using this library!
